language: objective-c
osx_image: xcode8.3
env:
  - TOOLCHAINS=swift
script:
  - swift package update
  - swift build
  - swift test
before_install:
  - TOOLCHAIN_BRANCH=swift-3.1-branch
  - TOOLCHAIN_VERSION=swift-3.1-DEVELOPMENT-SNAPSHOT-2017-03-27-a
  - curl -O https://swift.org/builds/${TOOLCHAIN_BRANCH}/xcode/${TOOLCHAIN_VERSION}/${TOOLCHAIN_VERSION}-osx.pkg
  - sudo installer -pkg ${TOOLCHAIN_VERSION}-osx.pkg -target /

