language: objective-c
osx_image: xcode9.2
env:
  - TOOLCHAINS=swift
script:
  - swift package update
  - swift build
  - swift test
before_install:
  - TOOLCHAIN_BRANCH=swift-4.0.3-release
  - TOOLCHAIN_VERSION=swift-4.0.3-RELEASE
  - curl -O https://swift.org/builds/${TOOLCHAIN_BRANCH}/xcode/${TOOLCHAIN_VERSION}/${TOOLCHAIN_VERSION}-osx.pkg
  - sudo installer -pkg ${TOOLCHAIN_VERSION}-osx.pkg -target /
  - unzip extern/hashfiles.zip -d extern

